---
- hosts: all
  sudo: true
  vars_files:
    - vars/main.yml
    - vars/sensitive_user_data.yml
  roles:
    - common
    - newrelic

- hosts: webserver
  sudo: true
  vars_files:
    - vars/main.yml
    - vars/sensitive_user_data.yml
  roles:
    - webserver

- hosts: database
  sudo: true
  vars_files:
    - vars/main.yml
    - vars/sensitive_user_data.yml
  roles:
    - database
