- name: Add Postgresql apt repo key
  shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

- name: Add postgresql.list file
  copy: src=files/postgresql.list dest=/etc/apt/sources.list.d/postgresql.list owner=root mode=0600

- name: install required postgresql packages
  apt: pkg={{item}} state=installed update-cache=yes
  with_items:
    - postgresql-9.3
    - postgresql-server-dev-9.3
    - postgresql-client-common
    - libpq-dev
    - pgadmin3

- name: Install required Python packages.
  easy_install: name={{item}}
  with_items:
  - psycopg2

- name: enable conf.d files for postgresql
  lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf
              insertafter="^#include_dir = 'conf.d'"
              line="include_dir = 'conf.d'"
              state=present

# - name: update postgres db configuration
#   template: src=templates/postgresql.conf dest=/etc/postgresql/9.1/main/postgresql.conf
#   notify:
#     - restart postgresql

# - name: update postgres client configuration
#   copy: src=files/pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
#   notify:
#     - restart postgresql

# - name: update kernel memory settings
#   copy: src=files/30-postgresql-shm.conf dest=/etc/sysctl.d/30-postgresql-shm.conf
#   notify:
#     - reload sysctl

- name: create superuser for {{user}}
  postgresql_user: name={{user}} role_attr_flags=SUPERUSER password={{ postgresql_superuser_password }}
  sudo_user: postgres
  sudo: true

- name: ensure database {{postgresql_dbname}} is created
  postgresql_db: name={{postgresql_dbname}}
  sudo_user: postgres
  sudo: true

- name: ensure user has access to database
  postgresql_user: db={{postgresql_dbname}} name={{postgresql_username}} password={{postgresql_password}} priv=ALL
  sudo_user: postgres
  sudo: true

- name: ensure tvguide has access to database
  postgresql_user: db={{postgresql_dbname}} name=tvguide priv=ALL
  sudo_user: postgres
  sudo: true

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{postgresql_username}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo_user: postgres
  sudo: true
