- name: create {{user}} as user
  user: name={{user}} password={{user_password}} createhome=yes shell=/bin/bash state=present groups=sudo generate_ssh_key=true
- name: make {{user}} a sandwich
  template: src=sudoers.d dest=/etc/sudoers.d/{{user}} mode=0640 owner=root
- name: set authorized_keys for {{user}}
  copy: src=authorized_keys dest={{home}}/.ssh/authorized_keys mode=0600 owner={{user}} group={{user}}
- name: prevent root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no"
  notify: restart ssh
