---
- name: Install required system packages.
  apt: pkg={{item}} state=installed update-cache=yes cache_valid_time=3600
  with_items: system_packages
- name: Set timezone to {{timezone}
  shell: cp /usr/share/zoneinfo/{{timezone}} /etc/localtime
- name: Set default locale LANG to {{default_locale}}
  lineinfile: >
    dest=/etc/default/locale
    line=LANG="{{default_locale}}"
    regexp='^LANG='
    state=present insertafter=BOF
- name: Set default locale LC_ALL to {{default_locale}}
  lineinfile: >
    dest=/etc/environment
    line='LC_ALL="{{default_locale}}"'
    regexp='^LC_ALL='
    state=present insertafter=BOF
- name: ntp should be running
  action: service name=ntp state=running
  when: ntp_enabled