---
system_packages:
  - build-essential
  - fail2ban
  - git
  - htop
  - libcurl4-openssl-dev
  - ntp
  - ntp
  - ntpdate
  - python-dev
  - python-setuptools
  - screen
  - software-properties-common
  - vim
  - zlib1g-dev