---
- name: install python-pycurl
  apt: pkg=python-pycurl state=latest

- name: 'install brightbox ruby expirimental repositories'
  apt_repository: repo=ppa:brightbox/ruby-ng state=present

- name: 'Install required apt packages'
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
    - ruby2.1
    - ruby2.1-dev

- name: install default gems
  gem: name={{item}} state=present
  with_items:
  - bundler
  - rack
  - rake